---
- name: Install Apache httpd
  yum:
    name: httpd
    state: latest

- name: Start and enable httpd service
  service:
    name: httpd.service
    state: started
    enabled: yes

- name: Insert firewalld rule for httpd
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
