---
- name: Install remi-release-7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install php
  yum:
    name:
      - php
      - php-gd
      - php-mbstring
      - php-mysql
    enablerepo: remi-php56
    state: latest
  notify: Restart httpd
