# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "oki2a24/centos-7-x86_64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, id: "http", auto_correct: true
#  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.verbose = "v"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
