export GTEST_ROOT="/usr/local/googletest"
export GTEST_INCLUDEDIR="${GTEST_ROOT}/googletest/include"
export GMOCK_INCLUDEDIR="${GTEST_ROOT}/googlemock/include"
export GMOCK_LIBDIR="${GTEST_ROOT}/mybuild/googlemock"
export GTEST_LIBDIR="${GTEST_ROOT}/mybuild/googlemock/gtest"