---
# mysql_secure_installation
# Enter current password for root (enter for none): 
# Set root password? [Y/n] Y
# New password: vagrant
# Re-enter new password: vagrant
# Remove anonymous users? [Y/n] Y
# Disallow root login remotely? [Y/n] Y
# Remove test database and access to it? [Y/n] Y
# Reload privilege tables now? [Y/n] Y
- name: Install python mysqldb module
  yum:
    name: MySQL-python
    state: latest

- name: Get temporary password
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: mysql_default_password

- name: test
  debug:
    msg: "{{ mysql_default_password.stdout }}"

    #- name: Set root password
    #  mysql_user:
    #    name: root
    #    host_all: yes
    #    login_password: "{{ mysql_default_password.stdout }}"
    #    password: "{{ mysql_root_password }}"
    #  notify: Restart mysql

- name: Change root user password
  command: mysql -u root -p'{{ mysql_default_password.stdout }}' --connect-expired-password -e "set password for root@'localhost'=password('{{ mysql_root_password }}');"
  ignore_errors: yes

- name: Create /root/.my.cnf
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  notify: Restart mysql

- name: Remove anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  notify: Restart mysql

- name: Get hostname
  command: hostname
  register: hostname
  changed_when: false
  failed_when: false

- name: Disallow root login remotely
  mysql_user:
    name: root
    host: "{{ hostname.stdout }}"
    state: absent
  notify: Restart mysql

- name: Remove test database and access to it
  mysql_db:
    name: test
    state: absent
  notify: Restart mysql
